#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
SUCCESSFUL_TESTS=()
LAST_HTTP_CODE=""
LAST_HTTP_BODY=""

# JSON formatting helper (supports jq, node, python3, or fallback)
format_json() {
  if command -v jq >/dev/null 2>&1; then
    jq . 2>/dev/null || cat
  elif command -v node >/dev/null 2>&1; then
    node -e '
      let b = "";
      process.stdin.on("data", d => b += d);
      process.stdin.on("end", () => {
        try { console.log(JSON.stringify(JSON.parse(b), null, 2)); }
        catch { console.log(b); }
      });
    ' 2>/dev/null || cat
  elif command -v python3 >/dev/null 2>&1; then
    python3 -m json.tool 2>/dev/null || cat
  else
    cat
  fi
}

# http_req METHOD ENDPOINT [JSON_BODY] [EXTRA_HEADER]
http_req() {
  local method="$1"
  local endpoint="$2"
  local body="${3:-}"
  local extra_header="${4:-}"
  local url="${BASE_URL}${endpoint}"
  local tmp_res; tmp_res=$(mktemp)
  local http_code

  if [[ -n "$body" ]]; then
    if [[ -n "$extra_header" ]]; then
      http_code=$(curl -s -o "$tmp_res" -w "%{http_code}" -X "$method" "$url" \
        -H "Content-Type: application/json" \
        -H "$extra_header" \
        -d "$body") || http_code="000"
    else
      http_code=$(curl -s -o "$tmp_res" -w "%{http_code}" -X "$method" "$url" \
        -H "Content-Type: application/json" \
        -d "$body") || http_code="000"
    fi
  else
    if [[ -n "$extra_header" ]]; then
      http_code=$(curl -s -o "$tmp_res" -w "%{http_code}" -X "$method" "$url" \
        -H "$extra_header") || http_code="000"
    else
      http_code=$(curl -s -o "$tmp_res" -w "%{http_code}" -X "$method" "$url") || http_code="000"
    fi
  fi

  LAST_HTTP_CODE="$http_code"
  LAST_HTTP_BODY=$(<"$tmp_res")
  rm -f "$tmp_res"
}

banner "Payment Processing API Test Wizard"

# ── Stage 1: Connectivity & Swagger Documentation ─────────────────────────
stage "Service Connectivity & API Documentation"
say "First, verify that the queue-system service is running and accessible."
ask BASE_URL "Enter the base URL (default http://localhost:3000):"
BASE_URL="${BASE_URL:-http://localhost:3000}"
BASE_URL="${BASE_URL%/}"  # strip trailing slash

step "Checking system health (GET /)..."
http_req "GET" "/"
printf '  %sHTTP Status: %s%s\n' "$BOLD" "$LAST_HTTP_CODE" "$RESET"
printf '%s\n' "$LAST_HTTP_BODY" | format_json | sed 's/^/    /'

if [[ "$LAST_HTTP_CODE" == "200" ]]; then
  printf '  %s✓ Health check passed! Service is operational.%s\n' "$GREEN" "$RESET"
  SUCCESSFUL_TESTS+=("Stage 1: Health check (GET / -> 200 OK)")
else
  warn "Health check returned $LAST_HTTP_CODE. Is the server running? (bun run start:dev)"
  if ! confirm "Continue anyway?"; then
    say "Exiting wizard. Start the server and run this wizard again."
    exit 1
  fi
fi

printf '\n'
step "Swagger UI documentation is available at ${BASE_URL}/docs"
if confirm "Open Swagger UI in your browser?"; then
  open_url "${BASE_URL}/docs"
fi
pause "Press Enter to proceed to POST /payments testing..."

# ── Stage 2: Submit Immediate Payment (POST /payments) ────────────────────
stage "Submit Immediate Payment (POST /payments)"
say "Submitting an immediate high-priority payment into the ingestion queue."
say "This initiates atomic idempotency leasing (ADR 0002) and queues the job in BullMQ."

DEFAULT_PAY_ID="pay_$(date +%s)_$((RANDOM % 9000 + 1000))"
ask PAYMENT_ID "Payment ID [Enter for '$DEFAULT_PAY_ID']:"
PAYMENT_ID="${PAYMENT_ID:-$DEFAULT_PAY_ID}"

ask AMOUNT "Amount in cents [Enter for 5000 = \$50.00]:"
AMOUNT="${AMOUNT:-5000}"

ask CURRENCY "Currency (3-letter ISO) [Enter for 'USD']:"
CURRENCY="${CURRENCY:-USD}"

ask GATEWAY "Gateway ID (stripe/paypal/adyen) [Enter for 'stripe']:"
GATEWAY="${GATEWAY:-stripe}"

ask PRIORITY "Priority (high/normal/low) [Enter for 'high']:"
PRIORITY="${PRIORITY:-high}"

PAYLOAD=$(cat <<EOF
{
  "id": "$PAYMENT_ID",
  "amount": $AMOUNT,
  "currency": "$CURRENCY",
  "customerId": "cust_wizard_$(date +%s)",
  "gatewayId": "$GATEWAY",
  "priority": "$PRIORITY",
  "maxRetries": 3,
  "metadata": {
    "source": "wizard-test",
    "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  }
}
EOF
)

CORR_ID="corr_wiz_$(date +%s)_$((RANDOM % 9000 + 1000))"
step "Sending POST /payments with X-Correlation-Id: $CORR_ID..."
http_req "POST" "/payments" "$PAYLOAD" "X-Correlation-Id: $CORR_ID"

printf '  %sHTTP Status: %s%s\n' "$BOLD" "$LAST_HTTP_CODE" "$RESET"
printf '%s\n' "$LAST_HTTP_BODY" | format_json | sed 's/^/    /'

if [[ "$LAST_HTTP_CODE" == "201" ]]; then
  printf '  %s✓ Payment queued successfully (201 Created)!%s\n' "$GREEN" "$RESET"
  SUCCESSFUL_TESTS+=("Stage 2: POST /payments (Immediate payment queued: $PAYMENT_ID)")
else
  warn "Unexpected response code: $LAST_HTTP_CODE (expected 201)"
fi
pause "Press Enter to proceed to idempotency replay test..."

# ── Stage 3: Atomic Idempotency Replay (POST /payments) ───────────────────
stage "Atomic Idempotency Replay (POST /payments)"
say "Testing Two-Phase Atomic Idempotency (ADR 0002)."
say "We will re-submit the EXACT same payment ID ($PAYMENT_ID) to verify:"
say "  1. No duplicate charge or double queue occurs."
say "  2. The server returns 200 OK with replayed: true and the stored payment record."

step "Re-submitting POST /payments with identical ID: $PAYMENT_ID..."
http_req "POST" "/payments" "$PAYLOAD" "X-Correlation-Id: ${CORR_ID}_replay"

printf '  %sHTTP Status: %s%s\n' "$BOLD" "$LAST_HTTP_CODE" "$RESET"
printf '%s\n' "$LAST_HTTP_BODY" | format_json | sed 's/^/    /'

if [[ "$LAST_HTTP_CODE" == "200" ]]; then
  printf '  %s✓ Idempotency verified! Returned 200 OK with completed record.%s\n' "$GREEN" "$RESET"
  SUCCESSFUL_TESTS+=("Stage 3: POST /payments (Idempotent replay returned 200 OK)")
elif [[ "$LAST_HTTP_CODE" == "409" ]]; then
  note "Received 409 Conflict: payment is currently processing under an active lease."
  note "Waiting 2 seconds for worker completion..."
  sleep 2
  http_req "POST" "/payments" "$PAYLOAD" "X-Correlation-Id: ${CORR_ID}_replay2"
  printf '  %sRetry HTTP Status: %s%s\n' "$BOLD" "$LAST_HTTP_CODE" "$RESET"
  printf '%s\n' "$LAST_HTTP_BODY" | format_json | sed 's/^/    /'
  if [[ "$LAST_HTTP_CODE" == "200" ]]; then
    printf '  %s✓ Idempotency verified after worker completion!%s\n' "$GREEN" "$RESET"
    SUCCESSFUL_TESTS+=("Stage 3: POST /payments (Idempotent replay verified)")
  fi
else
  warn "Expected 200 OK replay, got $LAST_HTTP_CODE."
fi
pause "Press Enter to proceed to multi-gateway concurrency test..."

# ── Stage 4: Multi-Gateway Routing & Isolation (POST /payments) ───────────
stage "Multi-Gateway Routing & Isolation (POST /payments)"
say "Testing Per-Gateway Queue Isolation (ADR 0001)."
say "Submitting a payment to an alternate gateway (paypal or adyen)."
say "Isolated queues ensure traffic and degradation on one gateway do not block another."

GW2="paypal"
[[ "$GATEWAY" == "paypal" ]] && GW2="adyen"
GW2_PAY_ID="pay_gw2_$(date +%s)_$((RANDOM % 9000 + 1000))"

GW2_PAYLOAD=$(cat <<EOF
{
  "id": "$GW2_PAY_ID",
  "amount": 2500,
  "currency": "EUR",
  "customerId": "cust_multi_$(date +%s)",
  "gatewayId": "$GW2",
  "priority": "normal",
  "maxRetries": 3,
  "metadata": {
    "gateway": "$GW2",
    "source": "wizard-multi-gateway"
  }
}
EOF
)

step "Sending POST /payments to gateway '$GW2'..."
http_req "POST" "/payments" "$GW2_PAYLOAD"
printf '  %sHTTP Status: %s%s\n' "$BOLD" "$LAST_HTTP_CODE" "$RESET"
printf '%s\n' "$LAST_HTTP_BODY" | format_json | sed 's/^/    /'

if [[ "$LAST_HTTP_CODE" == "201" ]]; then
  printf '  %s✓ Payment enqueued in isolated queue bull:payments:%s!%s\n' "$GREEN" "$GW2" "$RESET"
  SUCCESSFUL_TESTS+=("Stage 4: POST /payments (Multi-gateway routing to $GW2)")
else
  warn "Unexpected response code: $LAST_HTTP_CODE"
fi
pause "Press Enter to proceed to scheduled payment test..."

# ── Stage 5: Scheduled & Delayed Payment (POST /payments/scheduled) ──────
stage "Scheduled & Delayed Payment (POST /payments/scheduled)"
say "Testing Delayed Job Scheduling via BullMQ delay."
say "The payment will not be eligible for worker execution until the delay elapses."

DELAY_MS=10000
SCHED_PAY_ID="pay_sched_$(date +%s)_$((RANDOM % 9000 + 1000))"

SCHED_PAYLOAD=$(cat <<EOF
{
  "id": "$SCHED_PAY_ID",
  "amount": 7500,
  "currency": "USD",
  "customerId": "cust_sched_$(date +%s)",
  "gatewayId": "stripe",
  "priority": "normal",
  "delayMs": $DELAY_MS
}
EOF
)

step "Sending POST /payments/scheduled with delayMs: $DELAY_MS (10s delay)..."
http_req "POST" "/payments/scheduled" "$SCHED_PAYLOAD"
printf '  %sHTTP Status: %s%s\n' "$BOLD" "$LAST_HTTP_CODE" "$RESET"
printf '%s\n' "$LAST_HTTP_BODY" | format_json | sed 's/^/    /'

if [[ "$LAST_HTTP_CODE" == "201" ]]; then
  printf '  %s✓ Scheduled payment accepted and delayed (201 Created)!%s\n' "$GREEN" "$RESET"
  SUCCESSFUL_TESTS+=("Stage 5: POST /payments/scheduled (Delayed ${DELAY_MS}ms: $SCHED_PAY_ID)")
else
  warn "Unexpected response code: $LAST_HTTP_CODE"
fi
pause "Press Enter to proceed to validation testing..."

# ── Stage 6: Input Validation Guards (Negative Testing) ───────────────────
stage "Input Validation Guards (Negative Testing on POST /payments)"
say "Testing defensive validation guards on POST /payments."
say "The system must reject malformed requests with 400 Bad Request."

step "Test 6.1: Negative payment amount (-500)..."
INVALID_AMOUNT_PAYLOAD='{"id":"bad_amt_'$(date +%s)'","amount":-500,"currency":"USD","customerId":"c1","gatewayId":"stripe"}'
http_req "POST" "/payments" "$INVALID_AMOUNT_PAYLOAD"
printf '  %sHTTP Status: %s%s\n' "$BOLD" "$LAST_HTTP_CODE" "$RESET"
printf '%s\n' "$LAST_HTTP_BODY" | format_json | sed 's/^/    /'
if [[ "$LAST_HTTP_CODE" == "400" ]]; then
  printf '  %s✓ Correctly rejected invalid amount with 400 Bad Request.%s\n' "$GREEN" "$RESET"
else
  warn "Expected 400, got $LAST_HTTP_CODE"
fi

printf '\n'
step "Test 6.2: Invalid 2-letter currency ('US' instead of 3-letter ISO)..."
INVALID_CURR_PAYLOAD='{"id":"bad_cur_'$(date +%s)'","amount":1000,"currency":"US","customerId":"c1","gatewayId":"stripe"}'
http_req "POST" "/payments" "$INVALID_CURR_PAYLOAD"
printf '  %sHTTP Status: %s%s\n' "$BOLD" "$LAST_HTTP_CODE" "$RESET"
printf '%s\n' "$LAST_HTTP_BODY" | format_json | sed 's/^/    /'
if [[ "$LAST_HTTP_CODE" == "400" ]]; then
  printf '  %s✓ Correctly rejected invalid currency with 400 Bad Request.%s\n' "$GREEN" "$RESET"
else
  warn "Expected 400, got $LAST_HTTP_CODE"
fi

SUCCESSFUL_TESTS+=("Stage 6: POST /payments validation guards (Negative amount & invalid currency rejected)")
pause "Press Enter to proceed to saga verification..."

# ── Stage 7: Payment Lifecycle & Saga Audit (GET /payments/:id) ───────────
stage "Payment Lifecycle & Saga Audit Verification (GET /payments/:id)"
say "Inspecting the processed payment record ($PAYMENT_ID)."
say "Verifying the 3-step saga execution:"
say "  1. Reserve Funds (res_{id}_{ts})"
say "  2. Authorize & Charge (gateway call with circuit breaker & token bucket)"
say "  3. Settle & Audit (double-entry ledger settlement)"

step "Fetching GET /payments/$PAYMENT_ID..."
http_req "GET" "/payments/$PAYMENT_ID"
printf '  %sHTTP Status: %s%s\n' "$BOLD" "$LAST_HTTP_CODE" "$RESET"
printf '%s\n' "$LAST_HTTP_BODY" | format_json | sed 's/^/    /'

if [[ "$LAST_HTTP_CODE" == "200" ]]; then
  printf '  %s✓ Retrieved payment record and financial audit trail!%s\n' "$GREEN" "$RESET"
  SUCCESSFUL_TESTS+=("Stage 7: GET /payments/$PAYMENT_ID (Saga lifecycle verified)")
else
  warn "Payment lookup returned $LAST_HTTP_CODE."
fi
pause "Press Enter to proceed to telemetry & DLQ inspection..."

# ── Stage 8: Operational Telemetry & DLQ Inspection ──────────────────────
stage "Operational Telemetry & DLQ Inspection"
say "Inspecting live operational telemetry and Dead-Letter Queue (DLQ)."

step "Querying live metrics snapshot (GET /queues/metrics)..."
http_req "GET" "/queues/metrics"
printf '  %sHTTP Status: %s%s\n' "$BOLD" "$LAST_HTTP_CODE" "$RESET"
printf '%s\n' "$LAST_HTTP_BODY" | format_json | sed 's/^/    /'

printf '\n'
step "Querying Dead-Letter Queue (GET /queues/dlq)..."
http_req "GET" "/queues/dlq"
printf '  %sHTTP Status: %s%s\n' "$BOLD" "$LAST_HTTP_CODE" "$RESET"
printf '%s\n' "$LAST_HTTP_BODY" | format_json | sed 's/^/    /'

SUCCESSFUL_TESTS+=("Stage 8: GET /queues/metrics & GET /queues/dlq (Operational telemetry)")
pause "Press Enter to view final testing summary..."

# ── Closing Summary ───────────────────────────────────────────────────────
finish

printf '%s%s  ✓ API Test Wizard Completed Successfully%s\n\n' "$BOLD" "$GREEN" "$RESET"
for t in "${SUCCESSFUL_TESTS[@]}"; do
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$t"
done

printf '\n%sNext Steps:%s\n' "$BOLD" "$RESET"
note "  • View interactive Swagger UI: ${BASE_URL}/docs"
note "  • View metrics snapshot: curl -s ${BASE_URL}/queues/metrics | jq ."
note "  • Run full automated E2E test suite: bun run test:e2e"
printf '\n'
